hyper_params:
  problem: "double_integrator"
  architecture: "xtfc-unfreeze"
  analytical_pretraining: "xTQx"
  log_wandb: false
  bias: false

problem_params:
  in_dim: 2
  input_ranges: [[-1.0, 1.0], [-1.0, 1.0]]

  Q: [[1.0, 0.0], [0.0, 1.0]]
  R: [[0.1]]

training_params:
  hidden_units: [20]
  activation: "silu"
  n_colloc: 5000
  edge_sampling_weight: [0.2, 0.2]
  n_epochs: 10000

optimizer_params:
  optimizer: "adam"
  lr: 0.001

pretraining_params:
  n_pretraining_colloc: 1000
  lambda_reg: 0.000001