hyper_params:
  problem: "double_integrator"  # Does not do anything, just for reference
  architecture: "xtfc-unfreeze" # Does not do anything, just for reference
  analytical_pretraining: "xTQx"
  log_wandb: false
  bias: false

problem_params:
  in_dim: 2
  input_ranges: [[-1.0, 1.0], [-1.0, 1.0]]

  Q: [[10.0, 0.0], [0.0, 1.0]]
  R: [[1]]

  mass_bob: 0.2
  length_rod: 1.0
  gravity: 9.81

training_params:
  hidden_units: [50]
  activation: "silu"
  n_colloc: 5000
  edge_sampling_weight: [0.2, 0.2]
  n_epochs: 10000

optimizer_params:
  optimizer: "adam"
  lr: 0.001

pretraining_params:
  n_pretraining_colloc: 10000
  lambda_reg: 0.000001